apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: intune-python-export
  namespace: my-cronjob
spec:
  schedule: 30 0 * * *
  concurrencyPolicy: Allow
  suspend: false
  jobTemplate:
    metadata:
    spec:
      template:
        spec:
          containers:
            - name: intune-python-export
              # Replace <latest> with image ID
              image: >-
                intune-python-export:latest
              args:
                - /bin/sh
                - '-c'
                - python app.py
              envFrom:
                - secretRef:
                    # Create OpenShift Secrets using .env_template as a template
                    name: intune-python-export_dev_secrets
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: IfNotPresent
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1